# Generic WASI toolchain for ~/WASM* HolePunch family.
#   cmake -B build-wasi -DCMAKE_TOOLCHAIN_FILE=<this> -DWASI_SDK_PATH=...
if(NOT WASI_SDK_PATH)
  if(DEFINED ENV{WASI_SDK_PATH})
    set(WASI_SDK_PATH "$ENV{WASI_SDK_PATH}")
  else()
    set(WASI_SDK_PATH "$ENV{USERPROFILE}/wasi-sdk")
  endif()
endif()
file(TO_CMAKE_PATH "${WASI_SDK_PATH}" WASI_SDK_PATH)
if(NOT EXISTS "${WASI_SDK_PATH}/bin/clang.exe" AND NOT EXISTS "${WASI_SDK_PATH}/bin/clang")
  message(FATAL_ERROR "Set WASI_SDK_PATH to a wasi-sdk root (missing clang)")
endif()
set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
if(EXISTS "${WASI_SDK_PATH}/bin/clang.exe")
  set(CMAKE_C_COMPILER "${WASI_SDK_PATH}/bin/clang.exe")
  set(CMAKE_CXX_COMPILER "${WASI_SDK_PATH}/bin/clang++.exe")
  set(CMAKE_AR "${WASI_SDK_PATH}/bin/llvm-ar.exe")
  set(CMAKE_RANLIB "${WASI_SDK_PATH}/bin/llvm-ranlib.exe")
else()
  set(CMAKE_C_COMPILER "${WASI_SDK_PATH}/bin/clang")
  set(CMAKE_CXX_COMPILER "${WASI_SDK_PATH}/bin/clang++")
  set(CMAKE_AR "${WASI_SDK_PATH}/bin/llvm-ar")
  set(CMAKE_RANLIB "${WASI_SDK_PATH}/bin/llvm-ranlib")
endif()
set(CMAKE_C_COMPILER_TARGET wasm32-wasi)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasi)
set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(WHP_WASI ON)
set(WMP_WASI ON)
set(WEW_WASI ON)
set(WCE_WASI ON)
set(WOC_WASI ON)
set(WVT_WASI ON)
set(WIR_WASI ON)
set(WCM_WASI ON)
set(WPM_WASI ON)
set(WPC_WASI ON)
set(WPR_WASI ON)
set(WRM_WASI ON)
set(WFS_WASI ON)
set(WMC_WASI ON)
set(WLM_WASI ON)
