#ifndef WOW_C_TYPES_H_
#define WOW_C_TYPES_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef uint32_t WowHandle;
typedef uint32_t WowResult;

#define WOW_HANDLE_INVALID ((WowHandle)0)

#define WOW_RESULT_OK 0u
#define WOW_RESULT_CANCELLED 1u
#define WOW_RESULT_UNKNOWN 2u
#define WOW_RESULT_INVALID_ARGUMENT 3u
#define WOW_RESULT_DEADLINE_EXCEEDED 4u
#define WOW_RESULT_NOT_FOUND 5u
#define WOW_RESULT_ALREADY_EXISTS 6u
#define WOW_RESULT_PERMISSION_DENIED 7u
#define WOW_RESULT_RESOURCE_EXHAUSTED 8u
#define WOW_RESULT_FAILED_PRECONDITION 9u
#define WOW_RESULT_ABORTED 10u
#define WOW_RESULT_OUT_OF_RANGE 11u
#define WOW_RESULT_UNIMPLEMENTED 12u
#define WOW_RESULT_INTERNAL 13u
#define WOW_RESULT_UNAVAILABLE 14u

#define WOW_PACK_DRIVE 0
#define WOW_PACK_DAGGER 1

// Win32 occupancy surfaces. Isolation is thin at host / sys / ipc /
// compositor / hv / shell / tty / net — wasm SFI does not hold those hops.
#define WOW_SURFACE_HANDLE 0
#define WOW_SURFACE_KERNEL32 1
#define WOW_SURFACE_NTDLL 2
#define WOW_SURFACE_USER32 3
#define WOW_SURFACE_GDI32 4
#define WOW_SURFACE_OLE32 5
#define WOW_SURFACE_OLEAUT32 6
#define WOW_SURFACE_ADVAPI32 7
#define WOW_SURFACE_WS2 8
#define WOW_SURFACE_BCRYPT 9
#define WOW_SURFACE_NCRYPT 10
#define WOW_SURFACE_CRYPT32 11
#define WOW_SURFACE_SHELL32 12
#define WOW_SURFACE_WINHTTP 13
#define WOW_SURFACE_IPHLPAPI 14
#define WOW_SURFACE_VERSION 15
#define WOW_SURFACE_COMCTL32 16
#define WOW_SURFACE_WININET 17
#define WOW_SURFACE_DNSAPI 18
#define WOW_SURFACE_SECUR32 19
#define WOW_SURFACE_DBGHELP 20
#define WOW_SURFACE_SETUPAPI 21
#define WOW_SURFACE_NETAPI32 22
#define WOW_SURFACE_PDH 23
#define WOW_SURFACE_WEVTAPI 24
#define WOW_SURFACE_COMDLG32 25
#define WOW_SURFACE_WINHV 26
#define WOW_SURFACE_WINHV_EMU 27
#define WOW_SURFACE_WSLAPI 28
#define WOW_SURFACE_WSL 29
#define WOW_SURFACE_NIX 30
#define WOW_SURFACE_PROCESS 31
#define WOW_SURFACE_THREAD 32
#define WOW_SURFACE_FILE 33
#define WOW_SURFACE_HEAP 34
#define WOW_SURFACE_VMEM 35
#define WOW_SURFACE_PIPE 36
#define WOW_SURFACE_CONSOLE 37
#define WOW_SURFACE_REGISTRY 38
#define WOW_SURFACE_TOKEN 39
#define WOW_SURFACE_PE 40
#define WOW_SURFACE_HWND 41
#define WOW_SURFACE_NTOSKRNL 42
#define WOW_SURFACE_SYS_HEAP 43
#define WOW_SURFACE_OCCUPANCY_DRIVER 44
#define WOW_SURFACE_WIN32K 45
#define WOW_SURFACE_CMD 46
#define WOW_SURFACE_SH 47
#define WOW_SURFACE_WOW_KO 48
#define WOW_SURFACE_WASMTTY 49
#define WOW_SURFACE_GOCVM 50
#define WOW_SURFACE_CONPTY 51
#define WOW_SURFACE_PTS 52
#define WOW_SURFACE_SCTP 53
#define WOW_SURFACE_WNS 54
#define WOW_SURFACE_COUNT 55

#define WOW_DRIVER_OCCUPANCY 0
#define WOW_DRIVER_WIN32K 1
#define WOW_DRIVER_NTOSKRNL 2

#define WOW_KO_OCCUPANCY 0
#define WOW_KO_NTFS 1

#define WOW_IRP_MJ_CREATE 0x00
#define WOW_IRP_MJ_CLOSE 0x02
#define WOW_IRP_MJ_DEVICE_CONTROL 0x0e
#define WOW_IRP_MJ_INTERNAL_DEVICE_CONTROL 0x0f
#define WOW_IRP_MJ_PNP 0x1b
#define WOW_IRP_MJ_MAXIMUM_FUNCTION 0x1b
#define WOW_IRP_MJ_COUNT 0x1c
#define WOW_IRP_MN_START_DEVICE 0x00
#define WOW_IRP_MN_REMOVE_DEVICE 0x02

#define WOW_FILE_DEVICE_UNKNOWN 0x00000022u
#define WOW_DO_BUFFERED_IO 0x00000004u
#define WOW_SERVICE_KERNEL_DRIVER 1u

// Unique CTL_CODE range. Mojo 0x00222xxx / Skia 0x00223xxx. This hop
// maps Win32 catalog pages through IRP, not pipes or raster.
#define WOW_IOCTL_OCCUPY 0x00224000u
#define WOW_IOCTL_LOAD 0x00224004u
#define WOW_IOCTL_ATTACH 0x00224008u
#define WOW_IOCTL_MAP 0x0022400cu
#define WOW_IOCTL_INFO 0x00224014u
#define WOW_IOCTL_EXEC 0x00224018u
#define WOW_IOCTL_TTY 0x0022401cu
#define WOW_IOCTL_WIN32 0x00224020u

#define WOW_ISOLATION_SFI 0
#define WOW_ISOLATION_HOST 1
#define WOW_ISOLATION_SYS 2
#define WOW_ISOLATION_IPC 3
#define WOW_ISOLATION_COMPOSITOR 4
#define WOW_ISOLATION_HV 5
#define WOW_ISOLATION_SHELL 6
#define WOW_ISOLATION_TTY 7
#define WOW_ISOLATION_NET 8

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // WOW_C_TYPES_H_
